### ISSUE TITLE
Lunch Route Issue

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-android-client#21] opened 2016-01-08 18:44 UTC
I opened the app today (Friday 1/8 around 1pm.) during the lunch route and it said there were no trolleys and to check schedule. 

I then went to the map view and saw the trolley running. So, it seems the app is not pulling the route info for the Friday lunch route.

**Comment by ajhodges** [comment] 2016-01-09 16:50
I believe I have the fix for this particular bug. But this raises a good question about the design of the 'not running' popup. Right now it is set to show the dialog if the API returns no running trolleys. Maybe it makes more sense to tie the popup to the route schedule? (Show the popup if there is no route scheduled currently). Or maybe some combination of both?

The issue is that sometimes trolleys are running when there are no routes active, and users should be informed that they are out of service somehow.

**Comment by bikeoid** [comment] 2016-01-09 18:20
Yes, I think it will be best to tie it to the schedule.   I see them pop up frequently now that they're auto-on whenever there is ignition power.   That will also keep them from showing as available if they're on a  private function but out of the garage location.

**Comment by ajhodges** [comment] 2016-01-09 18:38
So you are saying I should also hide the trolley markers if there is no active route?

**Comment by bikeoid** [comment] 2016-01-09 19:04
That's a good question - I hadn't thought about it, but I'm leaning toward hiding them: if they're not available to ride, there's no value in knowing where they are.   

What do others think?

**Comment by ajhodges** [comment] 2016-01-09 19:17
I kind of think it makes sense to do, and that it would probably be simplest to do it server side IMO. Then we don't get trolleys popping up on the map (on any of the clients) when they're being warmed up for the day at 7am, or when they are being cleaned at midnight. Then I could change the "no trolleys available" message I currently have to a "no scheduled routes" message and not worry about the presence of the trolleys.

**Comment by bikeoid** [comment] 2016-01-09 19:26
I agree that it would be easier to fix this server side where it would immediately give the 3 apps consistent behavior.    But it's still useful for a debug function / Database Visualization - I could make a new API call for that purpose however.    

We'll see what others think about no data to the apps when there is no schedule.

**Comment by ajhodges** [comment] 2016-01-09 20:01
You could also use something like /api/v1/Trolleys/Running?showInactive=true for the debug mode

**Closed as completed** 2016-01-10 21:29 UTC
Labels: bug
